name       : kvirc
version    : 5.0.0
release    : 10
source     :
    - https://github.com/kvirc/KVIrc/archive/5.0.0.tar.gz : 452e683760221055f117d2ab4359aa432e01ce5d5e3abe80772b7a13a78b594a
homepage   : http://www.kvirc.net/
license    : GPL-2.0-or-later
component  : network.irc
summary    : The KVIrc IRC Client
description: |
    KVIrc is a free portable IRC client based on the excellent Qt GUI toolkit.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(enchant-2)
    - pkgconfig(phonon4qt5)
    - pkgconfig(python3)
    - pkgconfig(xcb)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
    - extra-cmake-modules
    - ki18n-devel
    - knotifications-devel
    - kservice-devel
    - kwindowsystem-devel
    - kxmlgui-devel
libsplit   : no
setup      : |
    %apply_patches
    %cmake_ninja \
        -DUSE_ENV_FLAGS=ON \
        -DWANT_DCC_VIDEO=ON \
        -DWANT_OGG_THEORA=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
